name: home_assignment_pintrest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.0
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  clerk_flutter: ^0.0.14-beta
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
